/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CardInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5641169758311934745L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CardInfo\",\"namespace\":\"com.training.kafka.avro\",\"fields\":[{\"name\":\"cardType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastFourDigits\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"expiryMonth\",\"type\":\"int\"},{\"name\":\"expiryYear\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CardInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CardInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CardInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CardInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CardInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CardInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CardInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CardInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CardInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String cardType;
  private java.lang.String lastFourDigits;
  private int expiryMonth;
  private int expiryYear;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CardInfo() {}

  /**
   * All-args constructor.
   * @param cardType The new value for cardType
   * @param lastFourDigits The new value for lastFourDigits
   * @param expiryMonth The new value for expiryMonth
   * @param expiryYear The new value for expiryYear
   */
  public CardInfo(java.lang.String cardType, java.lang.String lastFourDigits, java.lang.Integer expiryMonth, java.lang.Integer expiryYear) {
    this.cardType = cardType;
    this.lastFourDigits = lastFourDigits;
    this.expiryMonth = expiryMonth;
    this.expiryYear = expiryYear;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cardType;
    case 1: return lastFourDigits;
    case 2: return expiryMonth;
    case 3: return expiryYear;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cardType = value$ != null ? value$.toString() : null; break;
    case 1: lastFourDigits = value$ != null ? value$.toString() : null; break;
    case 2: expiryMonth = (java.lang.Integer)value$; break;
    case 3: expiryYear = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'cardType' field.
   * @return The value of the 'cardType' field.
   */
  public java.lang.String getCardType() {
    return cardType;
  }


  /**
   * Sets the value of the 'cardType' field.
   * @param value the value to set.
   */
  public void setCardType(java.lang.String value) {
    this.cardType = value;
  }

  /**
   * Gets the value of the 'lastFourDigits' field.
   * @return The value of the 'lastFourDigits' field.
   */
  public java.lang.String getLastFourDigits() {
    return lastFourDigits;
  }


  /**
   * Sets the value of the 'lastFourDigits' field.
   * @param value the value to set.
   */
  public void setLastFourDigits(java.lang.String value) {
    this.lastFourDigits = value;
  }

  /**
   * Gets the value of the 'expiryMonth' field.
   * @return The value of the 'expiryMonth' field.
   */
  public int getExpiryMonth() {
    return expiryMonth;
  }


  /**
   * Sets the value of the 'expiryMonth' field.
   * @param value the value to set.
   */
  public void setExpiryMonth(int value) {
    this.expiryMonth = value;
  }

  /**
   * Gets the value of the 'expiryYear' field.
   * @return The value of the 'expiryYear' field.
   */
  public int getExpiryYear() {
    return expiryYear;
  }


  /**
   * Sets the value of the 'expiryYear' field.
   * @param value the value to set.
   */
  public void setExpiryYear(int value) {
    this.expiryYear = value;
  }

  /**
   * Creates a new CardInfo RecordBuilder.
   * @return A new CardInfo RecordBuilder
   */
  public static com.training.kafka.avro.CardInfo.Builder newBuilder() {
    return new com.training.kafka.avro.CardInfo.Builder();
  }

  /**
   * Creates a new CardInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CardInfo RecordBuilder
   */
  public static com.training.kafka.avro.CardInfo.Builder newBuilder(com.training.kafka.avro.CardInfo.Builder other) {
    if (other == null) {
      return new com.training.kafka.avro.CardInfo.Builder();
    } else {
      return new com.training.kafka.avro.CardInfo.Builder(other);
    }
  }

  /**
   * Creates a new CardInfo RecordBuilder by copying an existing CardInfo instance.
   * @param other The existing instance to copy.
   * @return A new CardInfo RecordBuilder
   */
  public static com.training.kafka.avro.CardInfo.Builder newBuilder(com.training.kafka.avro.CardInfo other) {
    if (other == null) {
      return new com.training.kafka.avro.CardInfo.Builder();
    } else {
      return new com.training.kafka.avro.CardInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for CardInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CardInfo>
    implements org.apache.avro.data.RecordBuilder<CardInfo> {

    private java.lang.String cardType;
    private java.lang.String lastFourDigits;
    private int expiryMonth;
    private int expiryYear;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.kafka.avro.CardInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cardType)) {
        this.cardType = data().deepCopy(fields()[0].schema(), other.cardType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastFourDigits)) {
        this.lastFourDigits = data().deepCopy(fields()[1].schema(), other.lastFourDigits);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.expiryMonth)) {
        this.expiryMonth = data().deepCopy(fields()[2].schema(), other.expiryMonth);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.expiryYear)) {
        this.expiryYear = data().deepCopy(fields()[3].schema(), other.expiryYear);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CardInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.kafka.avro.CardInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.cardType)) {
        this.cardType = data().deepCopy(fields()[0].schema(), other.cardType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastFourDigits)) {
        this.lastFourDigits = data().deepCopy(fields()[1].schema(), other.lastFourDigits);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.expiryMonth)) {
        this.expiryMonth = data().deepCopy(fields()[2].schema(), other.expiryMonth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.expiryYear)) {
        this.expiryYear = data().deepCopy(fields()[3].schema(), other.expiryYear);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'cardType' field.
      * @return The value.
      */
    public java.lang.String getCardType() {
      return cardType;
    }


    /**
      * Sets the value of the 'cardType' field.
      * @param value The value of 'cardType'.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder setCardType(java.lang.String value) {
      validate(fields()[0], value);
      this.cardType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'cardType' field has been set.
      * @return True if the 'cardType' field has been set, false otherwise.
      */
    public boolean hasCardType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'cardType' field.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder clearCardType() {
      cardType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastFourDigits' field.
      * @return The value.
      */
    public java.lang.String getLastFourDigits() {
      return lastFourDigits;
    }


    /**
      * Sets the value of the 'lastFourDigits' field.
      * @param value The value of 'lastFourDigits'.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder setLastFourDigits(java.lang.String value) {
      validate(fields()[1], value);
      this.lastFourDigits = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastFourDigits' field has been set.
      * @return True if the 'lastFourDigits' field has been set, false otherwise.
      */
    public boolean hasLastFourDigits() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastFourDigits' field.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder clearLastFourDigits() {
      lastFourDigits = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiryMonth' field.
      * @return The value.
      */
    public int getExpiryMonth() {
      return expiryMonth;
    }


    /**
      * Sets the value of the 'expiryMonth' field.
      * @param value The value of 'expiryMonth'.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder setExpiryMonth(int value) {
      validate(fields()[2], value);
      this.expiryMonth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'expiryMonth' field has been set.
      * @return True if the 'expiryMonth' field has been set, false otherwise.
      */
    public boolean hasExpiryMonth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'expiryMonth' field.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder clearExpiryMonth() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'expiryYear' field.
      * @return The value.
      */
    public int getExpiryYear() {
      return expiryYear;
    }


    /**
      * Sets the value of the 'expiryYear' field.
      * @param value The value of 'expiryYear'.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder setExpiryYear(int value) {
      validate(fields()[3], value);
      this.expiryYear = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'expiryYear' field has been set.
      * @return True if the 'expiryYear' field has been set, false otherwise.
      */
    public boolean hasExpiryYear() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'expiryYear' field.
      * @return This builder.
      */
    public com.training.kafka.avro.CardInfo.Builder clearExpiryYear() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CardInfo build() {
      try {
        CardInfo record = new CardInfo();
        record.cardType = fieldSetFlags()[0] ? this.cardType : (java.lang.String) defaultValue(fields()[0]);
        record.lastFourDigits = fieldSetFlags()[1] ? this.lastFourDigits : (java.lang.String) defaultValue(fields()[1]);
        record.expiryMonth = fieldSetFlags()[2] ? this.expiryMonth : (java.lang.Integer) defaultValue(fields()[2]);
        record.expiryYear = fieldSetFlags()[3] ? this.expiryYear : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CardInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<CardInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CardInfo>
    READER$ = (org.apache.avro.io.DatumReader<CardInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.cardType);

    out.writeString(this.lastFourDigits);

    out.writeInt(this.expiryMonth);

    out.writeInt(this.expiryYear);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.cardType = in.readString();

      this.lastFourDigits = in.readString();

      this.expiryMonth = in.readInt();

      this.expiryYear = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.cardType = in.readString();
          break;

        case 1:
          this.lastFourDigits = in.readString();
          break;

        case 2:
          this.expiryMonth = in.readInt();
          break;

        case 3:
          this.expiryYear = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










