/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ErrorDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1088465357336565600L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ErrorDetails\",\"namespace\":\"com.training.kafka.avro\",\"fields\":[{\"name\":\"errorCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorCategory\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ErrorDetails> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ErrorDetails> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ErrorDetails> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ErrorDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ErrorDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ErrorDetails to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ErrorDetails from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ErrorDetails instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ErrorDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String errorCode;
  private java.lang.String errorMessage;
  private java.lang.String errorCategory;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ErrorDetails() {}

  /**
   * All-args constructor.
   * @param errorCode The new value for errorCode
   * @param errorMessage The new value for errorMessage
   * @param errorCategory The new value for errorCategory
   */
  public ErrorDetails(java.lang.String errorCode, java.lang.String errorMessage, java.lang.String errorCategory) {
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
    this.errorCategory = errorCategory;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return errorCode;
    case 1: return errorMessage;
    case 2: return errorCategory;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: errorCode = value$ != null ? value$.toString() : null; break;
    case 1: errorMessage = value$ != null ? value$.toString() : null; break;
    case 2: errorCategory = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'errorCode' field.
   * @return The value of the 'errorCode' field.
   */
  public java.lang.String getErrorCode() {
    return errorCode;
  }


  /**
   * Sets the value of the 'errorCode' field.
   * @param value the value to set.
   */
  public void setErrorCode(java.lang.String value) {
    this.errorCode = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Gets the value of the 'errorCategory' field.
   * @return The value of the 'errorCategory' field.
   */
  public java.lang.String getErrorCategory() {
    return errorCategory;
  }


  /**
   * Sets the value of the 'errorCategory' field.
   * @param value the value to set.
   */
  public void setErrorCategory(java.lang.String value) {
    this.errorCategory = value;
  }

  /**
   * Creates a new ErrorDetails RecordBuilder.
   * @return A new ErrorDetails RecordBuilder
   */
  public static com.training.kafka.avro.ErrorDetails.Builder newBuilder() {
    return new com.training.kafka.avro.ErrorDetails.Builder();
  }

  /**
   * Creates a new ErrorDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ErrorDetails RecordBuilder
   */
  public static com.training.kafka.avro.ErrorDetails.Builder newBuilder(com.training.kafka.avro.ErrorDetails.Builder other) {
    if (other == null) {
      return new com.training.kafka.avro.ErrorDetails.Builder();
    } else {
      return new com.training.kafka.avro.ErrorDetails.Builder(other);
    }
  }

  /**
   * Creates a new ErrorDetails RecordBuilder by copying an existing ErrorDetails instance.
   * @param other The existing instance to copy.
   * @return A new ErrorDetails RecordBuilder
   */
  public static com.training.kafka.avro.ErrorDetails.Builder newBuilder(com.training.kafka.avro.ErrorDetails other) {
    if (other == null) {
      return new com.training.kafka.avro.ErrorDetails.Builder();
    } else {
      return new com.training.kafka.avro.ErrorDetails.Builder(other);
    }
  }

  /**
   * RecordBuilder for ErrorDetails instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ErrorDetails>
    implements org.apache.avro.data.RecordBuilder<ErrorDetails> {

    private java.lang.String errorCode;
    private java.lang.String errorMessage;
    private java.lang.String errorCategory;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.kafka.avro.ErrorDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.errorCategory)) {
        this.errorCategory = data().deepCopy(fields()[2].schema(), other.errorCategory);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ErrorDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.kafka.avro.ErrorDetails other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.errorCategory)) {
        this.errorCategory = data().deepCopy(fields()[2].schema(), other.errorCategory);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'errorCode' field.
      * @return The value.
      */
    public java.lang.String getErrorCode() {
      return errorCode;
    }


    /**
      * Sets the value of the 'errorCode' field.
      * @param value The value of 'errorCode'.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder setErrorCode(java.lang.String value) {
      validate(fields()[0], value);
      this.errorCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'errorCode' field has been set.
      * @return True if the 'errorCode' field has been set, false otherwise.
      */
    public boolean hasErrorCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'errorCode' field.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder clearErrorCode() {
      errorCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.errorMessage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorCategory' field.
      * @return The value.
      */
    public java.lang.String getErrorCategory() {
      return errorCategory;
    }


    /**
      * Sets the value of the 'errorCategory' field.
      * @param value The value of 'errorCategory'.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder setErrorCategory(java.lang.String value) {
      validate(fields()[2], value);
      this.errorCategory = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'errorCategory' field has been set.
      * @return True if the 'errorCategory' field has been set, false otherwise.
      */
    public boolean hasErrorCategory() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'errorCategory' field.
      * @return This builder.
      */
    public com.training.kafka.avro.ErrorDetails.Builder clearErrorCategory() {
      errorCategory = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ErrorDetails build() {
      try {
        ErrorDetails record = new ErrorDetails();
        record.errorCode = fieldSetFlags()[0] ? this.errorCode : (java.lang.String) defaultValue(fields()[0]);
        record.errorMessage = fieldSetFlags()[1] ? this.errorMessage : (java.lang.String) defaultValue(fields()[1]);
        record.errorCategory = fieldSetFlags()[2] ? this.errorCategory : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ErrorDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<ErrorDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ErrorDetails>
    READER$ = (org.apache.avro.io.DatumReader<ErrorDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.errorCode);

    out.writeString(this.errorMessage);

    out.writeString(this.errorCategory);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.errorCode = in.readString();

      this.errorMessage = in.readString();

      this.errorCategory = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.errorCode = in.readString();
          break;

        case 1:
          this.errorMessage = in.readString();
          break;

        case 2:
          this.errorCategory = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










