/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum OrderEventType implements org.apache.avro.generic.GenericEnumSymbol<OrderEventType> {
  CREATED, CONFIRMED, SHIPPED, DELIVERED, CANCELLED, REFUNDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderEventType\",\"namespace\":\"com.training.kafka.avro\",\"symbols\":[\"CREATED\",\"CONFIRMED\",\"SHIPPED\",\"DELIVERED\",\"CANCELLED\",\"REFUNDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
