/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentEventType implements org.apache.avro.generic.GenericEnumSymbol<PaymentEventType> {
  INITIATED, AUTHORIZED, CAPTURED, DECLINED, REFUNDED, FAILED, CHARGEBACK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentEventType\",\"namespace\":\"com.training.kafka.avro\",\"symbols\":[\"INITIATED\",\"AUTHORIZED\",\"CAPTURED\",\"DECLINED\",\"REFUNDED\",\"FAILED\",\"CHARGEBACK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
