/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3671110003428746498L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentInfo\",\"namespace\":\"com.training.kafka.avro\",\"fields\":[{\"name\":\"paymentMethod\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"paymentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"paymentStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String paymentMethod;
  private java.lang.String paymentId;
  private java.lang.String paymentStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentInfo() {}

  /**
   * All-args constructor.
   * @param paymentMethod The new value for paymentMethod
   * @param paymentId The new value for paymentId
   * @param paymentStatus The new value for paymentStatus
   */
  public PaymentInfo(java.lang.String paymentMethod, java.lang.String paymentId, java.lang.String paymentStatus) {
    this.paymentMethod = paymentMethod;
    this.paymentId = paymentId;
    this.paymentStatus = paymentStatus;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return paymentMethod;
    case 1: return paymentId;
    case 2: return paymentStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: paymentMethod = value$ != null ? value$.toString() : null; break;
    case 1: paymentId = value$ != null ? value$.toString() : null; break;
    case 2: paymentStatus = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'paymentMethod' field.
   * @return The value of the 'paymentMethod' field.
   */
  public java.lang.String getPaymentMethod() {
    return paymentMethod;
  }


  /**
   * Sets the value of the 'paymentMethod' field.
   * @param value the value to set.
   */
  public void setPaymentMethod(java.lang.String value) {
    this.paymentMethod = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.String getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.String value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'paymentStatus' field.
   * @return The value of the 'paymentStatus' field.
   */
  public java.lang.String getPaymentStatus() {
    return paymentStatus;
  }


  /**
   * Sets the value of the 'paymentStatus' field.
   * @param value the value to set.
   */
  public void setPaymentStatus(java.lang.String value) {
    this.paymentStatus = value;
  }

  /**
   * Creates a new PaymentInfo RecordBuilder.
   * @return A new PaymentInfo RecordBuilder
   */
  public static com.training.kafka.avro.PaymentInfo.Builder newBuilder() {
    return new com.training.kafka.avro.PaymentInfo.Builder();
  }

  /**
   * Creates a new PaymentInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentInfo RecordBuilder
   */
  public static com.training.kafka.avro.PaymentInfo.Builder newBuilder(com.training.kafka.avro.PaymentInfo.Builder other) {
    if (other == null) {
      return new com.training.kafka.avro.PaymentInfo.Builder();
    } else {
      return new com.training.kafka.avro.PaymentInfo.Builder(other);
    }
  }

  /**
   * Creates a new PaymentInfo RecordBuilder by copying an existing PaymentInfo instance.
   * @param other The existing instance to copy.
   * @return A new PaymentInfo RecordBuilder
   */
  public static com.training.kafka.avro.PaymentInfo.Builder newBuilder(com.training.kafka.avro.PaymentInfo other) {
    if (other == null) {
      return new com.training.kafka.avro.PaymentInfo.Builder();
    } else {
      return new com.training.kafka.avro.PaymentInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentInfo>
    implements org.apache.avro.data.RecordBuilder<PaymentInfo> {

    private java.lang.String paymentMethod;
    private java.lang.String paymentId;
    private java.lang.String paymentStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.kafka.avro.PaymentInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[0].schema(), other.paymentMethod);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[2].schema(), other.paymentStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.kafka.avro.PaymentInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[0].schema(), other.paymentMethod);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[2].schema(), other.paymentStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'paymentMethod' field.
      * @return The value.
      */
    public java.lang.String getPaymentMethod() {
      return paymentMethod;
    }


    /**
      * Sets the value of the 'paymentMethod' field.
      * @param value The value of 'paymentMethod'.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder setPaymentMethod(java.lang.String value) {
      validate(fields()[0], value);
      this.paymentMethod = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentMethod' field has been set.
      * @return True if the 'paymentMethod' field has been set, false otherwise.
      */
    public boolean hasPaymentMethod() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'paymentMethod' field.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder clearPaymentMethod() {
      paymentMethod = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.String getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder setPaymentId(java.lang.String value) {
      validate(fields()[1], value);
      this.paymentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentStatus' field.
      * @return The value.
      */
    public java.lang.String getPaymentStatus() {
      return paymentStatus;
    }


    /**
      * Sets the value of the 'paymentStatus' field.
      * @param value The value of 'paymentStatus'.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder setPaymentStatus(java.lang.String value) {
      validate(fields()[2], value);
      this.paymentStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentStatus' field has been set.
      * @return True if the 'paymentStatus' field has been set, false otherwise.
      */
    public boolean hasPaymentStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentStatus' field.
      * @return This builder.
      */
    public com.training.kafka.avro.PaymentInfo.Builder clearPaymentStatus() {
      paymentStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentInfo build() {
      try {
        PaymentInfo record = new PaymentInfo();
        record.paymentMethod = fieldSetFlags()[0] ? this.paymentMethod : (java.lang.String) defaultValue(fields()[0]);
        record.paymentId = fieldSetFlags()[1] ? this.paymentId : (java.lang.String) defaultValue(fields()[1]);
        record.paymentStatus = fieldSetFlags()[2] ? this.paymentStatus : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentInfo>
    READER$ = (org.apache.avro.io.DatumReader<PaymentInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.paymentMethod);

    out.writeString(this.paymentId);

    out.writeString(this.paymentStatus);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.paymentMethod = in.readString();

      this.paymentId = in.readString();

      this.paymentStatus = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.paymentMethod = in.readString();
          break;

        case 1:
          this.paymentId = in.readString();
          break;

        case 2:
          this.paymentStatus = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










