/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethod> {
  CREDIT_CARD, DEBIT_CARD, PAYPAL, STRIPE, APPLE_PAY, GOOGLE_PAY, BANK_TRANSFER, CASH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"namespace\":\"com.training.kafka.avro\",\"symbols\":[\"CREDIT_CARD\",\"DEBIT_CARD\",\"PAYPAL\",\"STRIPE\",\"APPLE_PAY\",\"GOOGLE_PAY\",\"BANK_TRANSFER\",\"CASH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
