/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;
@org.apache.avro.specific.AvroGenerated
public enum ProductEventType implements org.apache.avro.generic.GenericEnumSymbol<ProductEventType> {
  CREATED, UPDATED, DELETED, STOCK_CHANGED, PRICE_CHANGED, RESTOCKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductEventType\",\"namespace\":\"com.training.kafka.avro\",\"symbols\":[\"CREATED\",\"UPDATED\",\"DELETED\",\"STOCK_CHANGED\",\"PRICE_CHANGED\",\"RESTOCKED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
