/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.training.kafka.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class VendorInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2543463906117302303L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VendorInfo\",\"namespace\":\"com.training.kafka.avro\",\"fields\":[{\"name\":\"vendorId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"vendorName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"rating\",\"type\":[\"null\",\"double\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VendorInfo> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VendorInfo> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VendorInfo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VendorInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VendorInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VendorInfo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VendorInfo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VendorInfo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VendorInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String vendorId;
  private java.lang.String vendorName;
  private java.lang.Double rating;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VendorInfo() {}

  /**
   * All-args constructor.
   * @param vendorId The new value for vendorId
   * @param vendorName The new value for vendorName
   * @param rating The new value for rating
   */
  public VendorInfo(java.lang.String vendorId, java.lang.String vendorName, java.lang.Double rating) {
    this.vendorId = vendorId;
    this.vendorName = vendorName;
    this.rating = rating;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return vendorId;
    case 1: return vendorName;
    case 2: return rating;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: vendorId = value$ != null ? value$.toString() : null; break;
    case 1: vendorName = value$ != null ? value$.toString() : null; break;
    case 2: rating = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'vendorId' field.
   * @return The value of the 'vendorId' field.
   */
  public java.lang.String getVendorId() {
    return vendorId;
  }


  /**
   * Sets the value of the 'vendorId' field.
   * @param value the value to set.
   */
  public void setVendorId(java.lang.String value) {
    this.vendorId = value;
  }

  /**
   * Gets the value of the 'vendorName' field.
   * @return The value of the 'vendorName' field.
   */
  public java.lang.String getVendorName() {
    return vendorName;
  }


  /**
   * Sets the value of the 'vendorName' field.
   * @param value the value to set.
   */
  public void setVendorName(java.lang.String value) {
    this.vendorName = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public java.lang.Double getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(java.lang.Double value) {
    this.rating = value;
  }

  /**
   * Creates a new VendorInfo RecordBuilder.
   * @return A new VendorInfo RecordBuilder
   */
  public static com.training.kafka.avro.VendorInfo.Builder newBuilder() {
    return new com.training.kafka.avro.VendorInfo.Builder();
  }

  /**
   * Creates a new VendorInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VendorInfo RecordBuilder
   */
  public static com.training.kafka.avro.VendorInfo.Builder newBuilder(com.training.kafka.avro.VendorInfo.Builder other) {
    if (other == null) {
      return new com.training.kafka.avro.VendorInfo.Builder();
    } else {
      return new com.training.kafka.avro.VendorInfo.Builder(other);
    }
  }

  /**
   * Creates a new VendorInfo RecordBuilder by copying an existing VendorInfo instance.
   * @param other The existing instance to copy.
   * @return A new VendorInfo RecordBuilder
   */
  public static com.training.kafka.avro.VendorInfo.Builder newBuilder(com.training.kafka.avro.VendorInfo other) {
    if (other == null) {
      return new com.training.kafka.avro.VendorInfo.Builder();
    } else {
      return new com.training.kafka.avro.VendorInfo.Builder(other);
    }
  }

  /**
   * RecordBuilder for VendorInfo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VendorInfo>
    implements org.apache.avro.data.RecordBuilder<VendorInfo> {

    private java.lang.String vendorId;
    private java.lang.String vendorName;
    private java.lang.Double rating;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.training.kafka.avro.VendorInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.vendorId)) {
        this.vendorId = data().deepCopy(fields()[0].schema(), other.vendorId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.vendorName)) {
        this.vendorName = data().deepCopy(fields()[1].schema(), other.vendorName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing VendorInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.training.kafka.avro.VendorInfo other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.vendorId)) {
        this.vendorId = data().deepCopy(fields()[0].schema(), other.vendorId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.vendorName)) {
        this.vendorName = data().deepCopy(fields()[1].schema(), other.vendorName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.rating)) {
        this.rating = data().deepCopy(fields()[2].schema(), other.rating);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'vendorId' field.
      * @return The value.
      */
    public java.lang.String getVendorId() {
      return vendorId;
    }


    /**
      * Sets the value of the 'vendorId' field.
      * @param value The value of 'vendorId'.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder setVendorId(java.lang.String value) {
      validate(fields()[0], value);
      this.vendorId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'vendorId' field has been set.
      * @return True if the 'vendorId' field has been set, false otherwise.
      */
    public boolean hasVendorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'vendorId' field.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder clearVendorId() {
      vendorId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'vendorName' field.
      * @return The value.
      */
    public java.lang.String getVendorName() {
      return vendorName;
    }


    /**
      * Sets the value of the 'vendorName' field.
      * @param value The value of 'vendorName'.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder setVendorName(java.lang.String value) {
      validate(fields()[1], value);
      this.vendorName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'vendorName' field has been set.
      * @return True if the 'vendorName' field has been set, false otherwise.
      */
    public boolean hasVendorName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'vendorName' field.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder clearVendorName() {
      vendorName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public java.lang.Double getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder setRating(java.lang.Double value) {
      validate(fields()[2], value);
      this.rating = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public com.training.kafka.avro.VendorInfo.Builder clearRating() {
      rating = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VendorInfo build() {
      try {
        VendorInfo record = new VendorInfo();
        record.vendorId = fieldSetFlags()[0] ? this.vendorId : (java.lang.String) defaultValue(fields()[0]);
        record.vendorName = fieldSetFlags()[1] ? this.vendorName : (java.lang.String) defaultValue(fields()[1]);
        record.rating = fieldSetFlags()[2] ? this.rating : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VendorInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<VendorInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VendorInfo>
    READER$ = (org.apache.avro.io.DatumReader<VendorInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.vendorId);

    out.writeString(this.vendorName);

    if (this.rating == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.rating);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.vendorId = in.readString();

      this.vendorName = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.rating = null;
      } else {
        this.rating = in.readDouble();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.vendorId = in.readString();
          break;

        case 1:
          this.vendorName = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.rating = null;
          } else {
            this.rating = in.readDouble();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










